package wci.frontend.pascal;

public enum PascalErrorCode {
	ALREADY_FORWARDED("Already specified in FORWARD"), 
	IDENTIFIER_REDEFINED("Redefined identifier"),
	IDENTIFIER_UNDEFINED("Undefined identifier"),
	INCOMPATIBLE_ASSIGNMENT("Incompatible assignment"),
	INCOMPATIBLE_TYPES("Incompatible types"),
	INVALID_ASSIGNMENT("Invalid assignment statement"),
	INVALID_CHARACTER("Invalid character"),
	INVALID_CONSTANT("Invalid constant"),
	INVALID_EXPONENT("Invalid exponent"),
	INVALID_EXPRESSION("Invalid expression"),
	INVALID_FIELD("Invalid field"),
	INVALID_FRACTION("Invalid fraction"),
	INVALID_IDENTIFIER_USAGE("Invalid identifier usage"),
  INVALID_INDEX_TYPE("Invalid index type"),
  INVALID_NUMBER("Invalid number"),
  INVALID_STATEMENT("Invalid statement"),
  INVALID_SUBRANGE_TYPE("Invalid subrange type"),
  INVALID_TARGET("Invalid assignment target"),
  INVALID_TYPE("Invalid type"),
  INVALID_VAR_PARM("Invalid VAR parameter"),
  MIN_GT_MAX("Min limit greater than max limit"),
  MISSING_BEGIN("Missing BEGIN"),
  MISSING_COLON("Missing :"),
  MISSING_COLON_EQUALS("Missing :="),
  MISSING_COMMA("Missing ,"),
  MISSING_CONSTANT("Missing constant"),
  MISSING_DO("Missing DO"),
  MISSING_DOT_DOT("Missing .."),
  MISSING_END("Missing END"),
  MISSING_EQUALS("Missing ="),
  MISSING_FOR_CONTROL("Invalid FOR control variable"),
  (""),
}